src/BlackSmurf/BusinessBundle/Entity/Bill.php
<?php

namespace BlackSmurf\BusinessBundle\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="BlackSmurf\BusinessBundle\Entity\BillRepository")
 * @ORM\Table(name="bill")
 */
class Bill {

    /**
     * @ORM\Id
     * @ORM\Column(type="string", length=14)
     * @var string
     */
    protected $id;

    /**
     * @ORM\OneToMany(targetEntity="Benefit", mappedBy="bill")
     * @var Benefit
     */
    protected $benefits;

    /**
     * @ORM\Column(type="string", length=50)
     * @var string
     */
    protected $title;

    /**
     * @ORM\Column(type="decimal", scale=2)
     * @var float
     */
    protected $totalPrice;

    /**
     * @ORM\Column(type="decimal", scale=2, options={"default":0})
     * @var float
     */
    protected $handoff;

    /**
     * @ORM\Column(type="decimal", scale=2, nullable=true)
     * @var float
     */
    protected $charges;

    /**
     * @ORM\Column(type="boolean", options={"default":false})
     * @var boolean
     */
    protected $accepted;

    /**
     * @ORM\Column(type="datetime")
     * @var DateTime
     */
    protected $date_initial;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     * @var DateTime
     */
    protected $date_accepted;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     * @var DateTime
     */
    protected $declared_date;

    /**
     * @ORM\ManyToOne(targetEntity="Client", inversedBy="bills")
     * @ORM\JoinColumn("clientId", referencedColumnName="id")
     * @var Client
     */
    protected $client;

    /**
     * @ORM\ManyToOne(targetEntity="Company", inversedBy="bills")
     * @ORM\JoinColumn("companySiret", referencedColumnName="siret")
     * @var Company
     */
    protected $company;

    /**
     * @ORM\Column(type="string", length=64, nullable=true)
     * @var string
     */
    protected $payment_reference;

    /**
     * @ORM\Column(type="integer", options={"default":0})
     * @var integer
     */
    protected $payment_mode;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     * @var DateTime
     */
    protected $payment_date;

    const NONE = 0;
    const CHECK = 1;
    const CREDIT_CARD = 2;
    const CASH = 3;
    const PAYPAL = 4;

    ////////////////////////////////////////////////////////////////////////////
    // MODIFIED CODE ///////////////////////////////////////////////////////////
    ////////////////////////////////////////////////////////////////////////////
    public function getTotalHandOffPrice() {
        if ($this->handoff != 0) {
            return $this->getTotalPrice() * (1 - $this->handoff / 100);
        }

        return $this->getTotalPrice();
    }

    ////////////////////////////////////////////////////////////////////////////
    // CODE ////////////////////////////////////////////////////////////////////
    ////////////////////////////////////////////////////////////////////////////
    /**
     * Constructor
     */
    public function __construct() {
        $this->benefits = new \Doctrine\Common\Collections\ArrayCollection();
    }

    /**
     * Set id
     *
     * @param string $id
     * @return Bill
     */
    public function setId($id) {
        $this->id = $id;

        return $this;
    }

    /**
     * Get id
     *
     * @return string
     */
    public function getId() {
        return $this->id;
    }

    /**
     * Set totalPrice
     *
     * @param string $totalPrice
     * @return Bill
     */
    public function setTotalPrice($totalPrice) {
        $this->totalPrice = $totalPrice;

        return $this;
    }

    /**
     * Get totalPrice
     *
     * @return string
     */
    public function getTotalPrice() {
        return $this->totalPrice;
    }

    /**
     * Set accepted
     *
     * @param boolean $accepted
     * @return Bill
     */
    public function setAccepted($accepted) {
        $this->accepted = $accepted;

        return $this;
    }

    /**
     * Get accepted
     *
     * @return boolean
     */
    public function getAccepted() {
        return $this->accepted;
    }

    /**
     * Set date_initial
     *
     * @param \DateTime $dateInitial
     * @return Bill
     */
    public function setDateInitial($dateInitial) {
        $this->date_initial = $dateInitial;

        return $this;
    }

    /**
     * Get date_initial
     *
     * @return \DateTime
     */
    public function getDateInitial() {
        return $this->date_initial;
    }

    /**
     * Set date_accepted
     *
     * @param \DateTime $dateAccepted
     * @return Bill
     */
    public function setDateAccepted($dateAccepted) {
        $this->date_accepted = $dateAccepted;

        return $this;
    }

    /**
     * Get date_accepted
     *
     * @return \DateTime
     */
    public function getDateAccepted() {
        return $this->date_accepted;
    }

    /**
     * Add benefits
     *
     * @param \BlackSmurf\BusinessBundle\Entity\Benefit $benefits
     * @return Bill
     */
    public function addBenefit(\BlackSmurf\BusinessBundle\Entity\Benefit $benefits) {
        $this->benefits[] = $benefits;

        return $this;
    }

    /**
     * Remove benefits
     *
     * @param \BlackSmurf\BusinessBundle\Entity\Benefit $benefits
     */
    public function removeBenefit(\BlackSmurf\BusinessBundle\Entity\Benefit $benefits) {
        $this->benefits->removeElement($benefits);
    }

    /**
     * Get benefits
     *
     * @return \Doctrine\Common\Collections\Collection
     */
    public function getBenefits() {
        return $this->benefits;
    }

    /**
     * Set title
     *
     * @param string $title
     * @return Bill
     */
    public function setTitle($title) {
        $this->title = $title;

        return $this;
    }

    /**
     * Get title
     *
     * @return string
     */
    public function getTitle() {
        return $this->title;
    }

    /**
     * Set client
     *
     * @param \BlackSmurf\BusinessBundle\Entity\Client $client
     * @return Bill
     */
    public function setClient(\BlackSmurf\BusinessBundle\Entity\Client $client = null) {
        $this->client = $client;

        return $this;
    }

    /**
     * Get client
     *
     * @return \BlackSmurf\BusinessBundle\Entity\Client
     */
    public function getClient() {
        return $this->client;
    }

    /**
     * Set company
     *
     * @param \BlackSmurf\BusinessBundle\Entity\Company $company
     * @return Bill
     */
    public function setCompany(\BlackSmurf\BusinessBundle\Entity\Company $company = null) {
        $this->company = $company;

        return $this;
    }

    /**
     * Get company
     *
     * @return \BlackSmurf\BusinessBundle\Entity\Company
     */
    public function getCompany() {
        return $this->company;
    }


    /**
     * Set charges
     *
     * @param float $charges
     * @return Bill
     */
    public function setCharges($charges) {
        $this->charges = $charges;

        return $this;
    }

    /**
     * Get charges
     *
     * @return float
     */
    public function getCharges() {
        return $this->charges;
    }

    /**
     * Set handoff
     *
     * @param string $handoff
     * @return Bill
     */
    public function setHandoff($handoff) {
        $this->handoff = $handoff;

        return $this;
    }

    /**
     * Get handoff
     *
     * @return string
     */
    public function getHandoff() {
        return $this->handoff;
    }

    /**
     * Set payment_reference
     *
     * @param string $paymentReference
     * @return Bill
     */
    public function setPaymentReference($paymentReference) {
        $this->payment_reference = $paymentReference;

        return $this;
    }

    /**
     * Get payment_reference
     *
     * @return string
     */
    public function getPaymentReference() {
        return $this->payment_reference;
    }

    /**
     * Set payment_mode
     *
     * @param integer $paymentMode
     * @return Bill
     */
    public function setPaymentMode($paymentMode) {
        $this->payment_mode = $paymentMode;

        return $this;
    }

    /**
     * Get payment_mode
     *
     * @return integer
     */
    public function getPaymentMode() {
        return $this->payment_mode;
    }

    /**
     * Set payment_date
     *
     * @param \DateTime $paymentDate
     * @return Bill
     */
    public function setPaymentDate($paymentDate) {
        $this->payment_date = $paymentDate;

        return $this;
    }

    /**
     * Get payment_date
     *
     * @return \DateTime
     */
    public function getPaymentDate() {
        return $this->payment_date;
    }


    /**
     * Set declared_date
     *
     * @param \DateTime $declaredDate
     * @return Bill
     */
    public function setDeclaredDate($declaredDate) {
        $this->declared_date = $declaredDate;

        return $this;
    }

    /**
     * Get declared_date
     *
     * @return \DateTime
     */
    public function getDeclaredDate() {
        return $this->declared_date;
    }


}

src/BlackSmurf/BusinessBundle/Form/BillType.php
<?php

namespace BlackSmurf\BusinessBundle\Form;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolverInterface;
use Doctrine\ORM\EntityRepository;

class BillType extends AbstractType {

    private $company;
    private $isNew;
    private $billId;

    public function __construct($company, $new, $billId) {
        $this->company = $company;
        $this->isNew = $new;
        $this->billId = $billId;
    }

    /**
     * @param FormBuilderInterface $builder
     * @param array $options
     */
    public function buildForm(FormBuilderInterface $builder, array $options) {

        $company = $this->company;

        $queryAnd = "1 = 1";
        if ($this->isNew) {
            $queryAnd = "b.bill is null";
        } else {
            $queryAnd = "(b.bill = " . $this->billId . " or b.bill is null)";
        }

        $builder
                ->add('title', 'text', array('label' => 'Nom de la facture :', 'max_length' => 255))
                ->add('totalPrice', 'number', array('label' => 'Montant total :', 'max_length' => 255, 'read_only' => true, 'attr' => array('style' => 'width: 80px')))
                ->add('handOff', 'number', array('label' => 'Remise (en %) :', 'max_length' => 255, 'required' => false, 'attr' => array('style' => 'width: 50px')))
                ->add('accepted', 'checkbox', array('label' => 'Devis accepté :', 'required' => false))
                ->add('client', 'entity', array(
                    'class' => 'BlackSmurf\BusinessBundle\Entity\Client',
                    'property' => 'name',
                    'empty_value' => null,
                    'query_builder' => function(EntityRepository $er) use ($company) {
                        return $er->createQueryBuilder('u')
                                ->where('u.company = :identifier')
                                ->setParameter('identifier', $company);
                    },
                    'label' => 'Client :'))
                ->add('benefits', 'entity', array(
                    'label' => 'Mes prestations',
                    'class' => 'BlackSmurf\BusinessBundle\Entity\Benefit',
                    'query_builder' => function(EntityRepository $er ) use ( $company, $queryAnd ) {
                        return $er->createQueryBuilder('b')
                                ->join('b.client', 'c')
                                ->where('c.company = :identifier')
                                ->andWhere($queryAnd)
                                ->setParameter('identifier', $company);
                    },
                    'required' => true,
                    'multiple' => true,
                    'expanded' => true))
        ;
    }

    /**
     * @param OptionsResolverInterface $resolver
     */
    public function setDefaultOptions(OptionsResolverInterface $resolver) {
        $resolver->setDefaults(array(
            'data_class' => 'BlackSmurf\BusinessBundle\Entity\Bill',
            'csrf_protection' => true,
            'csrf_field_name' => '_token',
        ));
    }

    /**
     * @return string
     */
    public function getName() {
        return 'blacksmurf_businessbundle_bill';
    }

}

src/BlackSmurf/BusinessBundle/Resources/views/Bill/form.html.twig
{% extends 'BlackSmurfSymfony2CoreBundle::index.html.twig' %}
{% block content %}
    {{ form_start(entityForm) }}
        <div class="error">{{ form_errors(entityForm) }}</div>
        {{ form_row(entityForm.title) }}
        {{ form_row(entityForm.client) }}
        {{ form_row(entityForm.totalPrice) }}
        {{ form_row(entityForm.handOff) }}
        <div class="form-group">
            <label class="col-sm-2 control-label required">Montant total remisé :</label>
            <div class="col-sm-10">
                <span id="smurf_businessbundle_bill_totalPrice_handOff" style="width: 80px" class="form-control">0,00</span>
            </div>
        </div>
        {{ form_row(entityForm.accepted) }}

        {{ form_errors(entityForm.benefits) }}
        <div class="panel-group" id="accordion" role="tablist" aria-multiselectable="true">
          <div class="panel panel-warning">
            <div class="panel-heading" role="tab" id="headingOne">
              <h4 class="panel-title">
                <a data-toggle="collapse" data-parent="#accordion" href="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
                  {{ form_label(entityForm.benefits) }}
                </a>
              </h4>
            </div>
            <div id="collapseOne" class="panel-collapse collapse in" role="tabpanel" aria-labelledby="headingOne">
              <div class="panel-body bill_benefit" style="font-size: 12px">
                <table class="dataTable">
                    <thead>
                        <tr>
                            <th style="width: 30px">Choix</th>
                            <th style="width: 45px">Date</th>
                            <th style="width: 50px">Montant</th>
                            <th>Client / Prestation</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for child in entityForm.benefits %}
                        {% set index = child.vars.value %}
                        <tr>
                            <td>{{ form_widget(child) }}</td>
                            <td><label for="smurf_businessbundle_bill_benefits_{{ choices[index].id }}">{{ choices[index].date|date('d/m/Y') }}</label></td>
                            <td style="text-align: right"><label for="smurf_businessbundle_bill_benefits_{{ choices[index].id }}"><span id="smurf_businessbundle_bill_benefits_{{ choices[index].id }}_value">{{ choices[index].price*choices[index].quantity }}</span> €</label></td>
                            <td><label for="smurf_businessbundle_bill_benefits_{{ choices[index].id }}">{{ choices[index].client.name }} - {{ choices[index].activity.name }}</label></td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
              </div>
            </div>
          </div>      
        </div>
        {% do entityForm.submit.setRendered %}
        {% do entityForm.benefits.setRendered %}
        {{ form_rest(entityForm) }}
        <br />
        <div style="text-align: right">
            <button type="button" class="btn btn-info" onclick="javascript:document.location.href = '{{ path(back_url) }}';">
                <span class="glyphicon glyphicon-chevron-left"></span> Précédent
            </button>&nbsp;
            <button type="button" id="form_submit" class="btn btn-danger" onclick="javascript:doCreate();">
                <span class="glyphicon glyphicon-floppy-saved"></span> Valider
            </button>
            <button type="submit" id="hidden_form_submit" style="visibility: hidden"></button>
        </div>
    {{ form_end(entityForm) }}

    <script>
        $(function() {
            computeTotalPriceWithHandOff();
        })
    </script>

{% endblock %}

src/BlackSmurf/BusinessBundle/Resources/views/Bill/index_client.html.twig
{% extends 'BlackSmurfSymfony2CoreBundle::index.html.twig' %}
{% set page_title = "Liste de mes devis/factures" %}
{% block content %}
    <table class="dataTable">
        <thead>
            <tr>
                <th style="width: 60px">Date</th>
                <th style="width: 80px">Numéro</th>
                <th>Désignation</th>
                <th style="width: 80px">Etat</th>
                <th style="width: 60px">Montant</th>
                <th style="width: 150px">Actions</th>
            </tr>
        </thead>
        <tbody>
            {% for bill in entities %}
                <tr>
                    <td>
                        {% if bill.accepted %}
                            {{ bill.dateAccepted|date('d/m/Y') }}
                        {% else %}
                            {{ bill.dateInitial|date('d/m/Y') }}
                        {% endif %}
                    </td>
                    <td>
                        {{ get_link(bill.id,
                                            {
                                                  "url": path('bill_benefits', { 'id': bill.id }),
                                                  "csrf": true
                                            }
                                    )
                        }}
                    <td>{{ bill.title }}</td>
                    <td>
                        {% if bill.accepted %}
                            {% if bill.paymentMode == 0 %}
                                Accepté
                            {% else %}
                                Payé
                                {%  if bill.paymentMode == 1 %}
                                    (Chèque)
                                {% elseif bill.paymentMode == 2 %}
                                    (CB)
                                {% elseif bill.paymentMode == 3 %}
                                    (Liquide)
                                {% elseif bill.paymentMode == 4  %}
                                    (Paypal)
                                {% endif %}
                            {% endif %}
                        {% else %}
                            En attente
                        {% endif %}
                    </td>
                    <td style="text-align: right"><b>{{ bill.totalHandOffPrice|number_format(2, ',', ' ') }} €</b></td>
                    <td style="text-align: center">
                        {{ get_link("Devis",
                                                { 
                                                  "url": path('bill_print', { 'id': bill.id, 'forceQuote': true }),
                                                  "icon": WidgetExtension.ICON_DOWNLOAD,
                                                  "csrf": true
                                                }
                                  )
                        }}
                        &nbsp;&nbsp;
                        {% if bill.accepted %}
                            {{ get_link("Facture",
                                                    { 
                                                      "url": path('bill_print', { 'id': bill.id }),
                                                      "icon": WidgetExtension.ICON_DOWNLOAD,
                                                      "csrf": true
                                                    }
                                      )
                            }}
                        {% else %}
                            {{ get_link("Accepter",
                                                    { 
                                                      "url": path('bill_accept', { 'id': bill.id }),
                                                      "icon": WidgetExtension.ICON_OK,
                                                        "method": "get",
                                                        "confirm":"Etes-vous sur de vouloir valider le devis " ~ bill.title ~ " ?",
                                                      "csrf": true
                                                }
                                      )
                            }}                            
                        {% endif %}
                    </td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
{% endblock %}

src/BlackSmurf/BusinessBundle/Resources/views/Bill/index_gest.html.twig
{% extends 'BlackSmurfSymfony2CoreBundle::index.html.twig' %}
{% set page_title = "Liste de mes devis/factures" %}
{% block content %}
    {{ get_button("Créer une nouvelle facture/devis", {
        "url": "javascript:document.location.href = '" ~ path('bill_new') ~ "'",
        "icon": WidgetExtension.ICON_PLUS
        })
    }}
    <table class="dataTable">
        <thead>
            <tr>
                <th style="width: 60px">Date</th>
                <th style="width: 80px">Numéro</th>
                <th>Désignation / Client</th>
                <th style="width: 80px">Etat</th>
                <th style="width: 80px">Montant</th>
                <th style="width: 180px">Actions</th>
            </tr>
        </thead>
        <tbody>
            {% for bill in entities %}
                <tr>
                    <td>
                        {% if bill.accepted %}
                            {{ bill.dateAccepted|date('d/m/Y') }}
                        {% else %}
                            {{ bill.dateInitial|date('d/m/Y') }}
                        {% endif %}
                    </td>
                    <td>
                        {{ get_link(bill.id,
                                            {
                                                  "url": path('bill_benefits', { 'id': bill.id }),
                                                  "csrf": true
                                            }
                                    )
                        }}                        
                    </td>
                    <td>{{ bill.title }} / {{ bill.client.name }}</td>
                    <td>
                        {% if bill.accepted %}
                            {% if bill.paymentMode == 0 %}
                                Accepté
                            {% else %}
                                Payé
                                {%  if bill.paymentMode == 1 %}
                                    (Chèque)
                                {% elseif bill.paymentMode == 2 %}
                                    (CB)
                                {% elseif bill.paymentMode == 3 %}
                                    (Liquide)
                                {% elseif bill.paymentMode == 4  %}
                                    (Paypal)
                                {% endif %}
                            {% endif %}
                        {% else %}
                            En attente
                        {% endif %}
                    </td>
                    <td style="text-align: right"><b>{{ bill.totalHandOffPrice|number_format(2, ',', ' ') }} €</b></td>
                    <td style="text-align: center">
                        {% if not bill.accepted %}
                            {{ get_link("Modifier",
                                                    { 
                                                      "url": path('bill_edit', { 'id': bill.id }),
                                                      "icon": WidgetExtension.ICON_EDIT,
                                                      "csrf": true
                                                    }
                                      )
                            }}                            
                            &nbsp;&nbsp;
                            {{ get_link("Supprimer",
                                                    { 
                                                      "url": path('bill_delete', { 'id': bill.id }),
                                                      "icon": WidgetExtension.ICON_REMOVE_CIRCLE,
                                                      "method": "delete",
                                                      "confirm":"Etes-vous sur de vouloir supprimer la facture " ~ bill.title ~ " ?",
                                                      "csrf": true
                                                    }
                                      )
                            }}
                            <br />
                            {{ get_link("Valider",
                                                    { 
                                                      "url": path('bill_accept', { 'id': bill.id }),
                                                      "icon": WidgetExtension.ICON_OK,
                                                      "csrf": true
                                                    }
                                      )
                            }}
                            &nbsp;&nbsp;
                        {% endif %}
                            {{ get_link("Devis",
                                                    { 
                                                      "url": path('bill_print', { 'id': bill.id, 'forceQuote': true }),
                                                      "icon": WidgetExtension.ICON_DOWNLOAD,
                                                      "csrf": true
                                                    }
                                      )
                            }}                            
                        {% if bill.accepted %}
                            &nbsp;&nbsp;{{ get_link("Facture",
                                                    { 
                                                      "url": path('bill_print', { 'id': bill.id }),
                                                      "icon": WidgetExtension.ICON_DOWNLOAD,
                                                      "csrf": true
                                                    }
                                      )
                            }}
                            <br />
                            {% if bill.paymentMode == 0 %}
                            &nbsp;&nbsp;{{ get_link("Facture payé...",
                                                    {
                                                        "url": path('bill_paid_form', { 'id': bill.id }),
                                                        "icon": WidgetExtension.ICON_CHECK,
                                                        "csrf": true
                                                    }
                                    )
                            }}
                            {% endif %}
                        {% else %}
                            <br />
                            {{ get_link("Notifier les clients",
                                        {
                                            "url": path('bill_notify', { 'id': bill.id }),
                                            "icon": WidgetExtension.ICON_ENVELOPE,
                                            "method": "get",
                                            "confirm":"Etes-vous sur de vouloir notifier les clients de la disponibilité du devis " ~ bill.title ~ " ?",
                                            "csrf": true
                                        }
                            )
                        }}
                        {% endif %}
                    </td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
{% endblock %}

src/BlackSmurf/BusinessBundle/Resources/views/Bill/list_benefits.html.twig
{% extends 'BlackSmurfSymfony2CoreBundle::index.html.twig' %}
{% set page_title = "Liste des prestations de la facture n°" ~ bill_id %}
{% block content %}
    <table class="dataTable">
        <thead>
            <tr>
                <th style="width: 60px">Date</th>
                <th style="width: 20px">Qté</th>
                <th>Type de prestation</th>
                <th style="width: 100px">Montant total</th>
            </tr>
        </thead>
        <tbody>
            {% for entity in entities %}
                <tr>
                    <td>{{ entity.date|date('d/m/Y') }}</td>
                    <td>{{ entity.quantity|number_format(2, ',', ' ') }}</td>
                    <td>{{ entity.activity.name }} - {{ entity.activity.description }}</td>
                    <td style="text-align: right"><b>{{ (entity.price * entity.quantity)|number_format(2, ',', ' ') }} €</b></td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
    <br /><br /><br />
    <div style="text-align: right; margin: 10px 0 0 0">
        {{ get_previous_button("Précédent", path(back_url)) }}
    </div>            
{% endblock %}

src/BlackSmurf/BusinessBundle/Resources/views/Bill/mail.html.twig
<p style="font-family: verdana, 'trebuchet ms', sans-serif">
    Bonjour {{ client_name }},<br />
    Le devis '{{ devis_name }}' vient d'être mis en ligne sur le portail <a href="{{ mylittlebusiness_uri }}">{{ mylittlebusiness_uri }}</a>.<br />
    Merci de bien vouloir vous connecter avec vos identifiants pour consulter le document.<br />
    <br />
    Bien cordialement,<br />
    <span style="font-weight: bold; text-transform: capitalize">{{ name }}</span><br />
    <br />
    <span style="font-size: 10px">
        <span style="font-weight: bold; text-transform: capitalize; font-style: italic">NO.SIREN</span> - {{ no_siren }}<br />
        <span style="font-weight: bold; text-transform: capitalize; font-style: italic">PHONE</span> - {{ phone_number }}<br />
        <span style="font-weight: bold; text-transform: capitalize; font-style: italic">W3</span> - <a href="{{ mylittlebusiness_uri }}">{{ mylittlebusiness_uri }}</a><br />
        <span style="font-weight: bold; text-transform: capitalize; font-style: italic">@</span> - {{ email }}<br />
    </span>
</p>

src/BlackSmurf/BusinessBundle/Resources/views/Bill/paidForm.html.twig
{% extends 'BlackSmurfSymfony2CoreBundle::index.html.twig' %}
{% block content %}

    {{ form_start(entityForm) }}
    {{ form_rest(entityForm) }}

    <br />
    <div style="text-align: right">
        <button type="button" class="btn btn-info" onclick="javascript:document.location.href = '{{ path(back_url) }}';">
            <span class="glyphicon glyphicon-chevron-left"></span> Précédent
        </button>&nbsp;
        <button type="button" id="form_submit" class="btn btn-danger" onclick="javascript:doCreate();">
            <span class="glyphicon glyphicon-floppy-saved"></span> Valider
        </button>
        <button type="submit" id="hidden_form_submit" style="visibility: hidden"></button>
    </div>
    {{ form_end(entityForm) }}
{% endblock %}